### ISSUE TITLE
Images don't show in Inkscape

### ISSUE THREAD

**Issue by ulpsbswivkbqcqebah** [felixfbecker/dom-to-svg#113]
Bitmap pictures of SVG output are not visible in free vector editor named Inkscape. The reason is probably because image href attribute should be xlink:href. I tried changing following lines localy (c:\Users\[username]\AppData\Roaming\Mozilla\Firefox\Profiles\[profilename].default\extensions\svg-screenshots@felixfbecker.xpi\src\) in (content|background).js(|.map) which solved the issue for me:

```ts
        // Inline binary images as base64 data: URL
        const dataUrl = await blobToDataURL(blob);
        element.dataset.src = element.href.baseVal;
        element.setAttribute('xlink:href', dataUrl.href);
```

Please include Inkscape to your testing software.

**Comment by eckynde** [comment]
This issue on the [Inkscape issue tracker](https://gitlab.com/inkscape/inbox/-/issues/620)
