### ISSUE TITLE
Is there a CDN version of dom to svg 

### ISSUE THREAD

**Issue by shibins** [felixfbecker/dom-to-svg#135]
Is there a CDN version of dom to svg  or can this executed from plain javascript

**Comment by shibins** [comment]
I tried to load index.js from browser and get index.js:24 Uncaught ReferenceError: exports is not defined

**Comment by Schweinepriester** [comment]
Not sure if that's what you desire, but via <https://stackoverflow.com/questions/63784737/how-do-i-import-blah-from-http-bar-org-some-esm-module-js-in-the-chrome-de> I made dom-to-svg work in the browser console like so:

```js
const { elementToSVG, inlineResources } = await import('https://cdn.skypack.dev/dom-to-svg');
```

- https://caniuse.com/es6-module-dynamic-import
- https://www.skypack.dev/view/dom-to-svg

**Comment by shibins** [comment]
> https://stackoverflow.com/questions/63784737/how-do-i-import-blah-from-http-bar-org-some-esm-module-js-in-the-chrome-de

Let try this

**Comment by felixfbecker** [comment]
Thanks for the suggestion @Schweinepriester! That's what I would recommend.
