### ISSUE TITLE
elementToSVG  x and  y positions  seems to be based on window or dom 

### ISSUE THREAD

**Issue by shibins** [felixfbecker/dom-to-svg#142]
I am using elementToSVG to convert html portion of page to svg .  but looks like the x and y positions  is based on the dom , is the way i can control this 

The code I am using 

elementToSVG(document.querySelector(contentId));

**Comment by felixfbecker** [comment]
I'm not sure if I understand the question, could you explain?

**Comment by shibins** [comment]
> I'm not sure if I understand the question, could you explain?

So I have multiple divs on my page . One is chart , another is table last one is ritch text ares (example of layout https://gridstackjs.com/)

Here each div block should  come to its own image with each dive moved top right corner

**Comment by shibins** [comment]
I think it was my issue . It seems to be working fine
