### ISSUE TITLE
Support for converting dom to svg for selected area  or multiple elements 

### ISSUE THREAD

**Issue by shibins** [felixfbecker/dom-to-svg#146]
I have requirement to Support for converting dom to svg for selected area  or multiple elements . is this possible ?

**Comment by felixfbecker** [comment]
Sure, just use `documentToSVG()` and pass the `captureArea` option (coordinates of the area you want to capture).

If you want to let the user select the area, it's relatively easy to write code that lets them select a rectangle with the mouse and get the bounds of that rectangle. See for example how the SVG Screenshot browser extension does it:

https://github.com/felixfbecker/svg-screenshots/blob/main/src/content.ts#L110:16

**Comment by shibins** [comment]
> Sure, just use `documentToSVG()` and pass the `captureArea` option (coordinates of the area you want to capture).
> 
> If you want to let the user select the area, it's relatively easy to write code that lets them select a rectangle with the mouse and get the bounds of that rectangle. See for example how the SVG Screenshot browser extension does it: https://github.com/felixfbecker/svg-screenshots/blob/main/src/content.ts#L110:16

Perfect . let me try

**Comment by shibins** [comment]
This solution worked
