### ISSUE TITLE
Mime types for SVG and MS Embedded OpenType fonts.

### ISSUE THREAD

**Issue by MartinGerritsen** [felixfbecker/dom-to-svg#155]
I am using primeicons for my project and on processing the font faces I am getting the following errors:

Error inlining http://localhost:9999/primeicons.eot?#iefix Error: Invalid response MIME type inlining font at http://localhost:9999/primeicons.eot?#iefix: Expected font MIME type, got application/vnd.ms-fontobject; charset=utf-8

Error inlining http://localhost:9999/primeicons.svg?#primeicons Error: Invalid response MIME type inlining font at http://localhost:9999/primeicons.svg?#primeicons: Expected font MIME type, got image/svg+xml; charset=utf-8

This can be fixed by changing and adding line 121 of inline.ts in your project:
`blob.type !== 'application/vnd.ms-fontobject'`
for:
`!blob.type.startsWith('image/svg+xml') && !blob.type.startsWith('application/vnd.ms-fontobject')`

**Comment by felixfbecker** [comment]
Wanna open a PR?
