### ISSUE TITLE
Less ambitious typescript target?

### ISSUE THREAD

**Issue by jonathon-love** [felixfbecker/dom-to-svg#2]
hi,

i notice the built .js files have lines like:

```
import { svgNamespace, isSVGImageElement, isSVGStyleElement } from './dom.js';
```

i'm finding that browserify barfs on these, and i have to incorporate babelify, etc. in order to use this library. i assume this is controlled by the `tsconfig.js` file, which specifies `"target": "ES2020",`. would it be possible to choose a less ambitious target? it would greatly simplify things for me, and probably others (it did take me quite a while to figure out how to use babelify).

with thanks

**Comment by felixfbecker** [comment]
Do you mean `import` statements? These are part of ES6 (ES2015), i.e. 5 years old. They are much easier to tree-shake than CommonJS, so I would be hesitant to switch to CommonJS. Given you already figured out how to setup Babelify now, is the problem solved for you?

**Comment by jonathon-love** [comment]
yeah ok. it's strange to me that browserify doesn't cope with these statements, given they're as old as you say. but if that's the situation ...

**Comment by felixfbecker** [comment]
browserify is a bit of a dated tool, I think they refused to add support for ESM because they were focused on allowing bundling of CommonJS NodeJS modules, not modern ES browser modules. Webpack, Rollup, Parcel etc all should have no problem with it :)

**Comment by jonathon-love** [comment]
yeah, i appreciate i'm not using what the cool kids are using. the error i get is:

```
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

i assume there's not a little tweak that will get it over the line with browserify?

with thanks
