### ISSUE TITLE
Error: Expected node to have data-z-index attribute

### ISSUE THREAD

**Issue by jonathon-love** [felixfbecker/dom-to-svg#3]
hi,

i didn't have this issue with the 0.02, but i'm experiencing it now in the 0.03. it is happening deep in the bowels of our application, so i'm hoping there's enough information here that you can see what it is. otherwise, i can try and put together a reproducible example.

`b.dataset.zIndex` is undefined.

<img width="1104" alt="Screen Shot 2020-11-02 at 21 47 19" src="https://user-images.githubusercontent.com/3240247/97859774-2e3b5c80-1d55-11eb-8400-198e5cc54383.png">

with thanks

**Comment by felixfbecker** [comment]
Interesting, I can't reproduce that in the test cases. A reproducible example would help a lot! You could for example give me a public URL, or save a HAR file in Chrome dev tools and I should be able to load that.

**Comment by jonathon-love** [comment]
what do you think about providing a webpage where we can provide html, and it generate the svg? i feel like this might be the easiest way for me (and people in general) to provide problematic html, and it would also be a good demo for the project. ?

**Comment by jonathon-love** [comment]
OK, this is my attempt to provide a reproducible example:

https://github.com/jonathon-love/dom-to-svg-stuff

note that this is throwing a different error than above ... but i suppose it's still throwing an error ...

**Comment by felixfbecker** [comment]
My main demo case for this project is this Chrome extension: https://chrome.google.com/webstore/detail/svg-screenshot/nfakpcpmhhilkdpphcjgnokknpbpdllg?hl=en-US
(it's a little behind the latest version though)

**Comment by felixfbecker** [comment]
I tried the example but I get no error, I added a `console.log()` for the SVG and it prints it to the console correctly. I'm using Chrome 86.0.4240.111. What error do you get?

**Comment by jonathon-love** [comment]
in firefox, i get

<img width="1293" alt="Screen Shot 2020-11-03 at 19 52 07" src="https://user-images.githubusercontent.com/3240247/97965241-2986af00-1e0e-11eb-9f3c-b2d18ee3d32a.png">

**Comment by felixfbecker** [comment]
Okay, looks like the error comes from the pretty-formatting, Firefox doesn't support `indent=yes` in XLST. I'll simply remove the `formatXML` function then as it doesn't make sense to bundle a whole custom XML formatter in this package. If you want pretty-formatted SVG, you could use some other XML formatter from npm (but even without formatting the SVG is valid SVG).

**Comment by felixfbecker** [comment]
This seems to be a different problem though then your original error. Do you have a repro for that by any chance?

**Comment by jonathon-love** [comment]
yeah, it's a different one. let me see if i can find a way to reproduce the other.

**Comment by jonathon-love** [comment]
OK, i've got it:

https://github.com/jonathon-love/dom-to-svg-stuff

jonathon

**Comment by jonathon-love** [comment]
the issue stems from these `clipPath`s not having a zIndex

https://github.com/felixfbecker/dom-to-svg/blob/main/src/element.ts#L123

but i'm not completely sure what the zIndex here should be ... should it simply be the same as `svgContainer`?

jonathon

**Comment by jonathon-love** [comment]
hi,

i'm happy to submit a PR, if you can give me a little advice on this one?

with thanks

**Comment by felixfbecker** [comment]
Should be fixed in the latest version!

**Comment by jonathon-love** [comment]
awesome. thanks.
