### ISSUE TITLE
Infinite recursion if page has style "span::before"

### ISSUE THREAD

**Issue by andreymal** [felixfbecker/dom-to-svg#96]
I found the "SVG Screenshot" extension on [Super User](https://superuser.com/a/1607301). In order to test it, I tried to take a screenshot of this particular Super User page.

But it hangs.

After some debugging I discovered that the hang is caused by this element near the Stack Exchange logo:

![](https://i.imgur.com/17azGDp.png)

When dom-to-svg handles `::before` pseudo-element, it creates a `span` child inside this `span` element. But the `span` child also has `::before` pseudo-element because of styles, and dom-to-svg handles the `span` child and creates another `span` child inside this `span` child. Since it also has `::before` pseudo-element, dom-to-svg handles it and creates `span` inside `span` inside `span`... and so on.

---

There is a minimal reproducible example. Try to `documentToSVG(document)` and it will hang.

```html
<!DOCTYPE html>
<html>
<head>
<style>
.foo span::before { content: "foo"; }
</style>
</head>
<body>
<div class="foo">
  <span>bar</span>
</div>
</body>
</html>
```

**Comment by felixfbecker** [comment]
Ah, that makes sense given the descendant selector.
